# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lsuS3Epo-qs1oGmH3pGovGdz3wgRXO8K
"""

li=[int(i) for i in  input('Enter values:').split()]
li.sort()
li.reverse()
print (li)

